### ISSUE TITLE
Owntracks "zerlegt" MQTT Gateway Config

### ISSUE THREAD

**Issue by christianTF** [Liver64/LoxBerry-Owntracks#1]
Hi Oliver,

https://github.com/Liver64/LoxBerry-Owntracks/blob/01b50182582a65155fe7ecbe7eb1169867302683/webfrontend/htmlauth/index.cgi#L577

Du schreibst hier deine Subscription direkt in meine mqtt.json. 
Allerdings habe ich das Format für Subscriptions in der mqtt.json geändert, deswegen schlägt nun das Gateway auf, wenn es deinen Eintrag liest.

Könntest du das bitte so ändern, dass du deine Subscriptions und Conversions entsprechend der dokumentierten Funktion erzeugst:
https://www.loxwiki.eu/display/LOXBERRY/MQTT+Gateway+for+plugin+developers#MQTTGatewayforplugindevelopers-Injectsubscriptions,conversion,resetAfterSendbyyourplugin

Du musst lediglich jeweils eine Datei in _dein_ Config-Verzeichnis legen:
mqtt_subscriptions.cfg
mqtt_conversions.cfg

In den Subscriptions steht Zeile für Zeile eine Subscription.
In den Conversions steht Zeile für Zeile eine Conversion.

lg, Christian

```
{
          'conversions' => [
                             'enter=1',
                             'leave=0',
                             'Home=1',
                             'Work=2'
                           ],
          'subscriptions' => [
                               {
                                 'toMS' => [],
                                 'id' => 'fhemluxtronik/#'
                               },
                               {
                                 'id' => 'owntracks/#',
                                 'toMS' => []
                               },
                               'owntracks/#'
                             ]
        }
```

Die ```owntracks/#``` Zeile ohne id => kommt von deinem Plugin, und beim Parsen im MQTT Gateway schlägt es auf.

**Comment by Liver64** [comment]
fixed both with Release v1.0.1
